name: deploy_prod

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted-ubuntu
    steps:
      - name: Poor-man CI/CD
        run: |
          echo "Poor-man CI/CD for deploy_prod"
